### ISSUE TITLE
Module "QtQuick.Controls" version 2.5 is not installed even with QtQuickControls 2.5 installed

### ISSUE THREAD

**Issue by NathanPB** [NathanPB/plasma5-genial#16]
# Reported by [adhesiveduck](https://www.pling.com/u/adhesiveduck/) on [pling](https://www.pling.com/)

> dtomlinson@debian:~/.local/share/plasma/plasmoids/dev.nathanpb.plasmagenial/contents/ui$ sudo apt list | grep qml-module-qtquick | grep installed
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> qml-module-qtquick-controls-styles-breeze/stable,now 4:5.14.5-1 amd64 [installed,automatic]
> qml-module-qtquick-controls2/stable,now 5.11.3+dfsg-2 amd64 [installed,automatic]
> qml-module-qtquick-controls/stable,now 5.11.3-2 amd64 [installed]
> qml-module-qtquick-dialogs/stable,now 5.11.3-2 amd64 [installed,automatic]
> qml-module-qtquick-extras/stable,now 5.11.3-2 amd64 [installed,automatic]
> qml-module-qtquick-layouts/stable,now 5.11.3-4 amd64 [installed,automatic]
> qml-module-qtquick-privatewidgets/stable,now 5.11.3-2 amd64 [installed,automatic]
> qml-module-qtquick-templates2/stable,now 5.11.3+dfsg-2 amd64 [installed,automatic]
> qml-module-qtquick-virtualkeyboard/stable,now 5.11.3+dfsg-2 amd64 [installed,automatic]
> qml-module-qtquick-window2/stable,now 5.11.3-4 amd64 [installed,automatic]
> qml-module-qtquick2/stable,now 5.11.3-4 amd64 [installed,automatic]
> 
> - 55 minutes ago
> Getting error
> 
> Error loading QML file: file:///home/dtomlinson/.local/share/plasma/plasmoids/dev.nathanpb.plasmagenial/contents/ui/main.qml:12:1: module "QtQuick.Controls" version 2.5 is not installed
> 
> On debian 10 with this.
> 
> root@debian:~$ apt list | grep qtquickcontrols
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> qtquickcontrols2-5-dev/stable,now 5.11.3+dfsg-2 amd64 [installed]
> qtquickcontrols2-5-doc-html/stable 5.11.3+dfsg-2 all
> qtquickcontrols2-5-doc/stable 5.11.3+dfsg-2 all
> qtquickcontrols2-5-examples/stable 5.11.3+dfsg-2 amd64
> qtquickcontrols5-doc-html/stable 5.11.3-2 all
> qtquickcontrols5-doc/stable 5.11.3-2 all
> qtquickcontrols5-examples/stable 5.11.3-2 amd64

**Comment by NathanPB** [comment]
Probably an incompatibility with Qt 5.11
Related: https://phabricator.kde.org/D24147

**Comment by dtomlinson91** [comment]
Thanks for picking this up so quickly, if you need any other logs/steps on my end I'm happy to provide. It's a fresh install of Debian 10 I reported it from.

**Comment by NathanPB** [comment]
> Thanks for picking this up so quickly, if you need any other logs/steps on my end I'm happy to provide. It's a fresh install of Debian 10 I reported it from.

No problem, I'm gonna test it as soon as I get home (internet connection speed issues). Probably downgrading the imports from ``QtQuick.Controls 2.5`` to ``QtQuick.Controls 2.4`` is a functional workaround, but I can't test it yet

**Comment by NathanPB** [comment]
I've been testing the Plasmoid in a Debian 10.1 live image this week, and we got serious problems with Qt 5.11. I have no fking idea why Debian is not updating Qt in its repositories, may have a reason.

For the most of the QML files, simply downgrading ``QtQuick.Controls 2.5`` to ``QtQuick.Controls 2.4`` solves the problem, but apparently the JavaScript interpreter is not the same and it causes lots of problems with the existent .js files.

I'm studying the specifications about the Qt 5.11 JavaScript Engine and I'll try to generate a separated versions for that kind of problem.

Sorry, @dtomlinson91 , this may take a little longer, but its my priority right now in this project

**Comment by NathanPB** [comment]
I had success on converting the most of the .js files from ES7 (Qt 5.13 compatible) to ES5 (Qt 5.11 compatible), but a lot about the project structure should be migrated (JS code inside QML).
(Sources: [Qt 5.11](https://doc-snapshots.qt.io/qt5-5.11/qtqml-javascript-hostenvironment.html) [Qt 5.13](https://doc-snapshots.qt.io/qt5-5.13/qtqml-javascript-hostenvironment.html))

The main problem in this moment is about the imports. Qt 5.11 use ``Qt.include("sourcefile.js")``, but Qt 5.13 uses the syntax ``.import "sourcefile.js" [as Alias]``. So I guess I will need to study a lot about transpilers and make my own Babel plugin with Qt transformations.
(Sources: [Qt 5.11](https://doc-snapshots.qt.io/qt5-5.11/qtqml-javascript-imports.html) [Qt 5.13](https://doc-snapshots.qt.io/qt5-5.13/qtqml-javascript-imports.html))

Again, it may take longer, compilers/transpilers/whateverthisthingis are not in my domain areas

**Comment by NathanPB** [comment]
Just found out that Babel does not provide any official APIs for parsing custom syntax. This issue is being a great challenge for me

**Comment by NathanPB** [comment]
Well I've been messing around with this issue for the last months and I actually found out its not worth providing support for Qt 5.11.

The problems are just too much to transpile the entire codebase to work at Qt 5.11, mainly because the import namespaces, so I just suggest update the Qt running in your machine to 5.13+. I have no idea why Debian is keeping Qt 5.11 in its repositories.

I'm sorry, but I'll have to left a "wontfix" :(

**Comment by danbulant** [comment]
Oh that sucks.

I have debian 10 with KDE Plasma and it kind of sucks to see I can't change my login screen because every theme uses new modules or something....

**Comment by shayneoneill** [comment]
Was this ever fixed?

**Comment by NathanPB** [comment]
> Was this ever fixed?

Nope, I had to just drop compatibility with Qt 5.11
